[package]
name = "puffin_http"
version = "0.1.0"
authors = ["Embark <opensource@embark-studios.com>"]
description = "HTTP server/client for puffin profiler data"
license = "MIT OR Apache-2.0"
edition = "2018"
homepage = "https://github.com/EmbarkStudios/puffin"
repository = "https://github.com/EmbarkStudios/puffin"
readme = "README.md"
categories = ["development-tools::profiling", "gui"]
keywords = ["profiler", "instrumentation", "gamedev"]
include = [ "**/*.rs", "Cargo.toml"]

[dependencies]
anyhow = "1"
bincode = "1.3"
log = "0.4"
puffin = { version = "0.5.2", path = "../puffin", features = ["with_serde"] }
retain_mut = "0.1.3"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
eframe = "0.12"
puffin_egui = { version = "0.3", path = "../puffin_egui" }
stderrlog = "0.5"
